### ISSUE TITLE
Memcached internal proxy work tracking

### ISSUE THREAD

**Issue by dormando** [memcached/memcached#827]
The embedded proxy (work history: #716) has been merged (#826). The main PR was too long and this issue gives me a chance to start fresh, and to do individual PR's for batches of work going forward without fear of needing to rebase the core of the proxy.

The proxy is *ready for preview and early testing*, we are still working on "productionizing" the proxy. This involves:
- Auditing for easy crash bugs
- Checking for common performance regressions
- Building out documentation and configuration libraries

We are targeting an "MVP" or "V1" version of proxy initially, which is a stabilization of the existing features. Once that is accomplished work will unblock on adding features.

MVP/V1 blockers:
- [x] Hunt down bugs, wrap up TODO's/FIXME's. (tracking in #862)
- [x] Add built-in ketama hashing for default key dist. (no weights; broken. added some hash compat modes)
- [x] fix `\r\n` handling in requests (looks like I actually did this at some point already)
- [x] Backend write combining (each req. to the same backend uses individual syscalls currently)
- [x]  io_uring mode for backend event thread. This is partially implemented but needs more work.
- [x] make io_uring usage a start-time option. (still requires optional compile, but can turn it off if something goes wrong/etc)
- [x] Run performance tests to validate basic performance level.
- [x] `stats settings` for proxy in use + if uring is enabled.
- [x] BUG: set-like commands that rely on `complete_nread_*` fail if proxy enabled but sets are not overridden.
- [x] BUG: lua fetches coroutine from main VM stack after reading set data, but it can interleave with other requests... thread needs to be ref'ed and ptr pulled instead. (fixed in #862)
- [x] Start proxy wiki page
- [x] Parallel in-flight request limiter (possible to just use existing resp object limiter?)
- [ ] Stats method for outputting configuration details (list of backend servers/route info)
- [x] lua functions for meta for flag testing and fast flag finding/editing. (routing all works fine, missing tests)
- [x] Get a reasonable set of routes for the "simple" lua library to start with.
- [ ] Optional: Get the simple library embedded in the daemon at build time.
- [x] Maybe: Methods for turning responses into set requests (without copying the value in/out of lua)
----
Post V1 major items:
- [ ] Config reload upgrade: centrally configure worker VM's and then swap the entire VM on reload, vs blocking each worker thread to perform reload work.
- [x] Ability to distribute requests to the local memcached cache.
- [ ] TLS support for mcmc library.
- [ ] Improve internal buffer management. (keep lua allocs tiny, larger allocs using cached objects)
- [ ] "compat" libs in the proxylibs repo. More lua examples.
- [ ] getaddrinfo (DNS) lookup cache. Will typically run in the config thread, but use IP's until this works better.
- [ ] second major TODO/FIXME scrub. I got nearly half of them in the first pass.
- [x] noreply/quiet support (could start by simply stripping them before sending to backend, else inserting `mn`'s)
- [x] allow N backend handler threads (worker threads pin to event threads)
- [x] allow run mode where worker threads handle backend events internally instead (one backend socket per worker thread)
- [x] ability to "route" from listener sockets (tag a socket with some text, match in lua)
- [x] improvements to resilience. just further hardening of the code against faults.

Fine detail level TODO items may appear here, or in specific PR's (that should get linked into this issue as they're opened)

**Comment by dormando** [comment]
I'm back on this... Bumping io_uring back into a v1 blocker since I feel we'll need the boost for now. Been making the code "work" and "not crash" but it won't be stable until it's restructured to not have SQE/CQE starvation issues under extreme/odd workloads. Also the backend write combining needs to be done, which will allow all syscalls for the backend thread to go through uring.

Need to make a decision on the second default distribution code (ketama + modern hashes vs multiprobe basically).

The actual test-and-validate work remains for v1 stability and is a huge grind. Basically need to sit and try to break it with whatever tools available until I feel like recommending it to people.

The last question mark is whether I put the extra effort into bundling the "simple" lua library on v1 or immediately afterward.

**Comment by dormando** [comment]
De-preffing io_uring again. I think it's stable enough for "preview" mode and I can iterate on it later. I asked the mailing list for some pro-tips on integration and got pointed at buggy/incomplete code which has soured me a bit. Have a standalone "benchmark" app I was using to figuring the uring interfaces which I'll just pick up again and figure out.

Need to pick and/or write the stdlib ketama-ish. Giving up on multi-probe consistent hashing for now since I don't have the time to lab it properly.

**Comment by dormando** [comment]
Performance notes:

I ran some basic tests with mc-crusher, mctester, latency-sampler, etc. on my 16 core ryzen 5950x to see where we are with performance. These tests were done over localhost connections. crusher -> proxy -> non-proxy memcached instance listening on multiple ports

Loaded a million small keys and fetched them randomly.
- 4 worker threads on proxy (3 and 5 were too low/high to saturate the proxy thread)
- Tested uring vs non-uring, with backend write combining.
- 5 memcached backends (all talking to the same instance, but 5x the tcp sockets/etc)
- Config is the `t/startfile.lua` from the base repo. So some logic is being applied to the fetch.

mc-crusher was running with:
`send=ascii_get,recv=blind_read,conns=20,key_prefix=/foo/,key_prealloc=0,pipelines=8,key_count=1000000`

I varied conn= and pipelines=, also used a multiget test:
`send=ascii_mget,recv=blind_read,conns=20,key_prefix=/foo/,key_prealloc=0,mget_count=50,key_count=1000000`

Also seeded with:
`send=ascii_set,recv=blind_read,conns=5,key_prefix=/foo/,key_prealloc=0,pipelines=4,key_count=1000000,stop_after=2000000,usleep=1000,value_size=10`
(bench-warmer works too)

latency-sampler ran on the same machine alongside this. I also set the cpu frequency governor from schedutil to performance for the test, but didn't otherwise try to tame turbo.

- no uring: averaged 600k rps on throughput (20 conns, 8 pipelines). Numbers moved linearly as number of connections and number of pipelines were adjusted up/down. Topping out around 800k. These are individual gets.
- during this test latency samples moved from the 10us to the 100us bucket.
- verified all traffic was actually hitting the backend memcached on different tcp sockets.
- With very low conn count, or sleeps added, latency samples would drop into the 10us bucket.

- with uring: similar numbers but +200k, so 800krps baseline. Latency profile was very close to nouring.
- with tuning, either way the backend seemed to top out around 900k-1mrps.

- with multiget: higher baseline numbers, but still maxing out around 1mrps.
- latency sampler now has most samples in 1008s, but some in the 1-10ms bucket (I should prob adjust program to split out the 1-10ms buckets). This makes sense with head of line blocking as many 50 multiget requests might be processed before the sampler's probe.

---

I did a second quick test of the lua engine without any backends:
`mcp.attach(mcp.CMD_GET, function(r) return "END\r\n" end)`

... which means we engage the proxy lua engine, but aren't routing requests.

Similar tests as above (skipping uring since it's not used without backends) showed throughput at 4-5 million rps, with latency samples in 100us range.

---

**What this means**: since it's just a quick set of tests, I was looking for pathological failures. ie; massive intermittent slowdowns, latency probe outliers, crashes/memory leaks/etc. With a very basic test I didn't see any of that.

- I did confirm the bottleneck is the dedicated backend thread, which we knew.
- Further optimizations to that code will yield good results. Currently uring mode handles reads but not writes, so there're some easy future wins.
- lua has a lot of optimizations on the table, but for most users it appears that it isn't a fundamental slowdown.
- Inline responses (ie; L1 caching for hot objects) have a high performance ceiling.
- Using proxy logic on end nodes vs border routers has good performance characteristics still.
- Adding the future mode to have each worker thread have its own backend connections will have a high peformance ceiling (this is post-v1).

More real world tests over network connections are needed but now is a good time for a spot check for any major issues. I don't presently see anything sticking out, so any issues that exist will require triggering error or uncommon conditions.

**Comment by dormando** [comment]
For what it's worth for those following: smaller/trivial changes I'm putting directly into the `next` branch. Larger changes and series get PR's like normal. A large related set of bugfixes will probably also get a branch.

After the perf testing and a few other fixes I'm basically down to ... the bug hunt, I guess. Probably a lot of them are already noted in TODO's/FIXME's so that's what I'll be trawling through tomorrow if I get to it. Will probably work on the simple library parallel to bugfixing since that'll help with code coverage.

**Comment by dormando** [comment]
The list of FIXME/TODO's that look like they should be v1 blockers is fairly huge... more than half are just simple error handling or code audits. We'll see how much of a slog this is I guess.

**Comment by dormando** [comment]
Known-TODO/FIXME cleanups going on in #862 - trying to avoid deep rewrites of the parser to use rbuf's for now. Some of the error handling improvements will have to wait until post-MVP but I'm ensuring the deeper functions are at least throwing proper errors. The parser needs a bit of work to get the error handling working to avoid mystifying errors.

**Comment by dormando** [comment]
Lots of non-code work this week but trying to ensure I chip at the blocker TODO/FIXME items every day. Down to 42 left for further inspection/repair. Punted a few more to post-v1 and fixed a bunch of things. I'll probably merge the progress into `next` tomorrow (friday) and cut out another release soon.

**Comment by dormando** [comment]
Lots of solid error handling and stability fixes going in... but I'll probably hold merging into `next` until I all or most of these important TODO/FIXME's addressed. Most of the remaining work is in the lua pool initializer and the parser... Looks like when I rewrote the way pools worked I got about 60% of the way through it and left some planned work. Needs a few fixups so I can keep the interface more stable after declaring v1.

**Comment by dormando** [comment]
Latest push has added missing main features to the `mcp.pool()` object (see startfile.lua). This reorganizes the function a bit as well, so the proxylibs ketama lib has been updated a bit to match. The default algo is currently jump with xxhash instead of murmur with modulus since I can't think of any reason why modulus would be better.

still need to write up a ketama module for folks who need it, but not done yet. I might punt that to post-v1, even. It's not hard to do but priority wise working on the lua simple probably is probably higher.

18 more TODO/FIXME's left, then I can merge that branch in and start back on the issues here.

**Comment by dormando** [comment]
Mass of TODO/FIXME fixes is a slog... the remaining 7 non-v2's are "Should be done soon but can be interleaved with other work or done post v1 without major issue". Still need to spend more time writing tests, but I think I'll do that by working on the simple interface.

Will probably cut another release shortly so I can have another in the 1.6.x series as there are some bugfixes I don't want people to avoid and I'll probably call the proxy-works-ish version 1.7.0.

The rest of the v1 blockers are kinda sorta maybe blockers vs just "do it really soon". At this point the proxy should be usable and I need to start splitting time between documentation and libraries.

Finally, thinking the last thing I should do pre-v1 is split the proxy file into multiple .c's. Was looking over the code and it looks like it's settled into some obvious splits already.

**Comment by dormando** [comment]
Detouring from finalizing for some observability improvements: https://github.com/memcached/memcached/pull/869

**Comment by dormando** [comment]
Missed a couple days. Working through the simple lib now. Think I'm going to change the `mcp.await` interface slightly.

Right now it will look for OK status (not a backend error) and HIT before adding to the result table, if you ask for it to wait for a specific number of items. Else it will return all results error or not. Think I'll add a simple state addition:
`mcp.await(request, pools, mcp.AWAIT_RES_ANY, 1)` - which would return the first result, regardless of status.
I might also do a simple internal wrapper and flatten this to:
`mcp.await(request, pools, count)` - return after count HIT's, else return whole table.
`mcp.await_any(request, pools, count)` - return after count results of any type
`mcp.await_noerror(request, pools, count)` - return after count non-error results (ie; MISS/HIT/etc)

Looking over the mcrouter routes, there's an "initialroute" route where the first specified zone gets returned and the rest stay async (error or not). I might skip this for now and do it later with extra code (since a result object or the IO object need to know their await positions? or at least an "await_first" bool I guess).

Writing this out is noisy but I think just helped me with the syntax, sorry :)

Almost all of the mcrouter routes can be implemented in terms of `mcp.await` with these tiny adjustments to the valid conditions. Except that await() must be the final route right now.

**Comment by dormando** [comment]
Wrapped up the await changes. The different acceptance modes only matter for early-return situations, so the final syntax is `mcp.await(request, pools, count, mcp.AWAIT_GOOD)` wherein there're a few options for validating early-return responses.

**Comment by dormando** [comment]
thinking about one more fundamental change to `mcp.await()` - presently if you give it a "count" to wait for, and now a flag for what types of responses to wait for, it'll only return those valid responses that were collected while waiting.

Instead it should gather responses regardless of return code, but early-return if enough "valid" responses are seen. Except for "AWAIT_FIRST" - which should probably only return the result from the first query.

Since this function is a lowish level tool that lets you return an observed error/miss state in the case of all requests failing.

**Comment by dormando** [comment]
Documentation is started here: https://github.com/memcached/memcached/wiki/Proxy

**Comment by dormando** [comment]
Very low on known-blockers... what I want to do before calling this "1.7.0" is probably mostly improvements to the `simple` library and the ketama-ish builtin lib. Not moving very fast this week as I did a lot the last few weeks and hoping for some feedback.

Also think I should add some API funcs for taking value-responses and making set requests from them (for recache on miss flows) since that's easyish and unblocks a lot for users.

There are, of course, nearly infinite other things to improve at this point and I could iterate forever, but I need to decide on what 1.7.0 looks like and what these last few additions are :)

**Comment by dormando** [comment]
Got a little miffed at the backend interface and refactored a bit: https://github.com/memcached/memcached/pull/873

Pulling the ketama lib in as the second default... There're no weights because that breaks the algo apparently. It does have some compat modes for a few other types of common clients.

The "default" mode when ketama's in use will xxhash the key and xxhash the entry point instead of md5. I wanted to not ship md5 in the code but having the working compat modes out of the box was too enticing...

**Comment by dormando** [comment]
Well I've held "v1" for a few weeks longer than I probably needed to... but I'm going to put my foot down and say next week will see 1.7.0 with the intro blog post. Core code wise I don't think anything would _really_ block it, and most of these should be done soon.

After reflecting on this for a while the remaining big ticket is `simple` lib. I need to put some real time in to give it a more "batteries included" feel. The better `simple` is the better we'll be out the gate. I need examples for pool expansion/contraction, recaching, more general mcrouter coverage, etc. This user library would have been a great thing for user collaboration but I might just have to throw my brain at it next week until I'm happy enough to announce.

There's plenty to do post 1.7.0 but my thinking is a bit clouded since this project has taken so long I feel like it should've been more solid than v1 was looking a few weeks back. It feels a bit better now.

**Comment by dormando** [comment]
maybe:

- response-into-set ability.. recache on miss is a pretty big missing feature
- noreply/q support.. just need to follow the logic on _responses_ for a v1, which might not be hard. Noreply/q gets stripped going to the backend. Then at least we have nearly-full protocol support.
- meta binary keys (then with above we would have full protocol support)
- bunch of await examples to add to simple? pool transition modes?
- do nothing but write unit tests and run torture tests for several days.

I completely failed at delivering an 0.1 since this now looks damn close to a 1.0 (maybe 0.8? Bah).

**Comment by dormando** [comment]
I hate getting sick... been trying to dedicate time to writing unit tests and hammering on it. Probably need to create a fake server for the unit tests so we can trigger various error conditions on demand.

**Comment by MarkRose** [comment]
I'm really happy to see this. We're currently using mcrouter and it uses a very high amount of CPU.

**Comment by dormando** [comment]
@MarkRose - Cool! Feel free to give it a try (some docs are in the wiki) and let me know what's missing for you. 1.6.15 is up to date with development as of today if that makes it any easier. I can help with configuration examples and/or expand the lua libraries.

There's a lot of work left but we need folks to give it a shake at this point.

**Comment by dormando** [comment]
Just merged in a replacement for `proxycmds` watch stream: `proxyreqs` + `mcp.log_req*` API calls to generate them. This should alleviate a few complaints about logging not being very detailed, but it comes at some cost when in use. (https://github.com/memcached/memcached/pull/887)

I've been not productive on this for a couple weeks.. The only thing holding me back from tagging this as v1 is a paranoia of bugs and wishing the `simple` library were more fleshed out. I've been looking at finally integrating C level unit testing so I can thoroughly mock-test the deep-down state machines that carry the most potential for causing problems. This wasn't historically easy/possible for the project but the newer code should be fine.

**Comment by dormando** [comment]
after a long break... just cut 1.6.16 with a bunch more fixes and updates.

still blocking on calling this generally available. I think backend TLS support is going to be required, and I will have to just invest some time in the `simple` library myself coming up with use cases and testing them out. Other than that all I want is to improve test coverage and I think it'll be a safe point to iterate from.

**Comment by dormando** [comment]
Looking pretty good I think.. might even bump TLS support to post-v1 but leave high priority.

Got a long list of optimizations and things to tweak/improve but the last pre-public consumption bit is probably the lua library and testing, so unless things come up I will spend the next 2-3 days on that and see what it's looking like. I should aim to have examples of various complications, plus the simple/etc for a lot of the common route types.

It should then be possible to write quickstart tutorials that don't require deep understanding of the proxy or lua but can still do a fair amount of useful work.

**Comment by MarkRose** [comment]
I haven't put it in production yet but have been playing with it. It did take me a while to understand the configuration, reading the file from the test suite.

If I were to suggest a simple example configuration, it would be to have simple replication of everything between three nodes without pooling or sharding. This kind of configuration arises in small cloud public cloud deployments.

**Comment by dormando** [comment]
@MarkRose Apologies for the obtuseness; polish is what I keep trying to get to but the goalposts move :)

have you seen the simple lib from https://github.com/memcached/memcached-proxylibs yet? That's what I'm trying to build out this week. If you have common mcrouter configs I'd love to hear it; I'll work first on what I know is a priority for folks.

RE: your example, can you explain just a bit more about how the keys are accessed? If I understand correctly, and since we only "think" in pools, that would be like: 3 pools with 1 backend each, with writes going to all three and reads going to one, any, or all? (but not sharded, so equivalent to one single backend)

**Comment by dormando** [comment]
Adding more to simple here: https://github.com/memcached/memcached-proxylibs/pull/2 as I get random ideas.

Still need to beef up the tests a bit.

A little lost on how to close this out as 1.7.0, so I might just not do that yet. What I'll do is ... see how far I get with tests this week, update the wiki docs, and draft a blog post of a quick start but explicitly state it's still experimental Then cut another 1.6 and upload the blog at the same time. Should also try to get a few more backlog issues/PR's merged.

I'll keep fiddling around with tests, library, APIs, and random TODO/FIXME items for the rest of august and consider the first release in september as 1.7.0.

**Comment by MarkRose** [comment]
@dormando I wasn't aware of proxylibs! May I suggest linking to it in the documentation of memcached?

What I meant by sharding would perhaps be better described as routing: using just a single pool without routing. Replicated across zones in a cloud deployment.

**Comment by dormando** [comment]
@MarkRose it is linked: https://github.com/memcached/memcached/wiki/Proxy#quick-start

I'm about to merge a largeish change to `simple`: https://github.com/memcached/memcached-proxylibs/pull/2 if you want to take a look. includes a README file and a bunch of cleanups.

The "flat" routing mode in simple is exactly what you're asking for.

**Comment by MarkRose** [comment]
@dormando Ah, in the wiki, not in the committed documentation. I didn't think to check there 🙃

`basic-replicate.lua` will probably be a very popular use-case. Those examples make things easy to understand. Looks good!

**Comment by dormando** [comment]
@MarkRose from the `doc/` in the tarball you mean? I'm not sure which proxy docs you saw before, haha.

There are a lot of potential features as I can make almost anything work that people request. If you give it a shot please let us know how it goes.

**Comment by MarkRose** [comment]
@dormando I didn't see any proxy docs. I was reading `startfile.lua` and `proxy.t` to figure it out :D

I do have one suggestion for a Lua example: get "my_zone" from an environment variable. Whether running as a virtual machine or pod in Kubernetes, doing this would allow the same image to be used without boot-time configuration. It's a simple `os.getenv("MEMCACHE_MYZONE")`, but it may be a useful hint to those unfamiliar with lua if included in a comment.

**Comment by dormando** [comment]
@MarkRose gotcha. yeah that was the docs for my other early adopters... as I said in this issue a few times I'm in polish mode before I go back to doing features.

I added your example to the simple PR, thanks!

**Comment by dormando** [comment]
merged in the simple changes, simple has docs, updated the wiki docs... fixed buildbots... need to add builders for proxy tests still but not sure if I'll bother yet.

prepping for a release which should fix a missing file issue and update compat for the simple.lua. just waiting/hoping for user testing on a couple more open PR's.

**Comment by dormando** [comment]
Just pinging this issue again: a loooot of things have been merged. I should've been ref'ing this PR with the other PR's.

Many stability and performance fixes have been merged, as well as improved API. Local cache access and "worker threads handle IO connections" PR's are in testing now. I'm also adding a ton of unit tests.

When those merge I'll update this issue.

I'd say we're at "MVP" or "V1" today, as it is getting much harder to find crashes and bugs. The only thing holding me back from wider advertising is lack of polish and more features in an included config library. If you happen to see this issue and are interested please speak up.

**Comment by dormando** [comment]
1.6.19 is out with tons of stability fixes and new features.

**Comment by dormando** [comment]
going to close this work issue. users should follow release notes at this point since it's been merged for a long time.
